
spring:
  application:
    name: base-rabbitmq-smart-home

mqtt:
  client-id: client-1
  default-topic: push_message_topic
  server-client-id: server-1
  servers: tcp://192.168.126.100:1883
  username: admin
  password: admin

server:
  port: 7777